### ISSUE TITLE
NoMethodError:   undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by idabmat** [teamcapybara/capybara#1975]
## Meta
Capybara Version: 2.18.0
Driver Information (and browser if relevant): selenium-webdriver 3.9.0 with Mobile Safari on IOS through Appium

## Expected Behavior
```ruby
within '.some_parent_class' do
  find('.some_class).click 
  find('.some_class2).click
end
```
should not raise an error

## Actual Behavior
The second `find` is raising a NoMethodError: undefined method `+' for nil:NilClass
Coming from https://github.com/teamcapybara/capybara/blob/2.18_stable/lib/capybara/selenium/node.rb#L211

## Steps to reproduce
Could not extract a reproducible case.

I see the code has changed substantially wih https://github.com/teamcapybara/capybara/commit/dfaf958ea7b9f02f31986f253ee10e6314853389 but I was not able to tell bundler to load the gem from master.

**Comment by idabmat** [comment]
I was able to test on master. The same error was raised from
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/node.rb#L181

**Comment by twalpole** [comment]
Is your code actually missing the 's at the end of the selectors, or is that a typo?

**Comment by twalpole** [comment]
If the missing 's is just a typo, what exactly does the first click do?  Does it happen to remove the '..some_class2' element from the page?

**Comment by idabmat** [comment]
The missing `'` was indeed a typo when I typed it in here.
The first click injects the element with class `.some_class2` into the DOM.
Here is the full rspec failure with stacktrace:
```
  1) Checkout on iPhone 8 and Safari Adding to cart and moving to checkout                                                                       
     Failure/Error: find('.go-market')
                                                                                                                                
     NoMethodError:                                                                                                                      
       undefined method `+' for nil:NilClass                                                                                    
     Shared Example Group: "Adding to cart and moving to checkout" called from ./spec/features/checkout_spec.rb:14                       
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/selenium/node.rb:211:in `path'  
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/node/element.rb:374:in `inspect'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/queries/selector_query.rb:56:in `description'    
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:37:in `find'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Ses
sion>'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/shared/checkout.rb:37:in `block (3 levels) in <top (required)>'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/session.rb:341:in `within'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/capybara-2.18.0/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
     # ./spec/shared/checkout.rb:34:in `block (2 levels) in <top (required)>'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_si
ngleton_context_hooks'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_exampl
e_hooks'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_c
ontext_hooks'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples
'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_spec
s'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_spec
s'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/me/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
     # /home/me/.asdf/installs/ruby/2.5.0/bin/rspec:23:in `load'
     # /home/me/.asdf/installs/ruby/2.5.0/bin/rspec:23:in `<main>'
```
