### ISSUE TITLE
Calling #set on a hidden checkbox obeys the global `allow_label_click` option

### ISSUE THREAD

**Issue by ibrahima** [teamcapybara/capybara#2090]
## Meta
**Capybara Version:**
**2.12** (though I'm trying to see if my test suite works with 2.18 and 3.6 and will upgrade if it helps)

**Driver Information (and browser if relevant):**
selenium-webdriver **3.12.0** with **Chrome 68.0.3440.75** (headless)

## Expected Behavior

This is a feature request for `set` to behave the same way that `check`/`uncheck`/`choose` work, for radio options and checkboxes.

Context: I have CSS that hides the native checkboxes and uses a `::before` psuedo-element on the label to draw a custom checkbox element. Thus, clicks on the checkbox will fail by default, whereas clicking on the label will work as expected.

example code

```ruby
# in rails_helper.rb
Capybara.configure do |config|
  config.automatic_label_click = true
end

# in a spec
find_all('input[type=checkbox]').each { |checkbox| checkbox.set(true) }
```

It would be nice if this would be sufficient to allow the `set` calls to succeed. It would also be nice if `set` accepted the `allow_label_click` option, but since this is global CSS in my project it makes sense to apply the configuration globally.

## Actual Behavior

```
Selenium::WebDriver::Error::UnknownError:
  unknown error: Element <input type="checkbox" name="checkboxName" id="checkboxName" value="1"> is not clickable at point (421, 211). Other element would receive the click: <label class="checkbox-label form--label form--checkboxLabel">...</label>
    (Session info: headless chrome=68.0.3440.75)
    (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.110-hyper x86_64)
```

## Steps to reproduce

SCSS (modified from my application; assume that `@include fa('icon-name')` includes the font-awesome character designated)

```scss
/* Hide the checkbox off-screen */
input[type="checkbox"] {
  position: absolute;
  clip: rect(1px, 1px, 1px, 1px);
}

.form--checkboxLabel {
  padding-left: 22px;

  &::before {
    @include fa('square-o');
    display: inline-block;
    position: absolute;
    top: -2px;
    left: 0;
    margin-right: 10px;
  }
}

input[type="checkbox"]:checked {
  + .form--checkboxLabel {
    color: green;
  }

  + .form--checkboxLabel::before {
    @include fa('check-square');
    color: green;
  }
}
```
Code snippet (repeated from above)
```ruby
# in rails_helper.rb
Capybara.configure do |config|
  config.automatic_label_click = true
end

# in a spec
find_all('input[type=checkbox]').each { |checkbox| checkbox.set(true) }
```

## Notes

Relates to https://github.com/teamcapybara/capybara/issues/1920, where the OP there mentioned not being able to use `set` on a checkbox because it does not have/obey the `allow_label_click` option (which can be configured globally).

It seems like the change that would be needed is for `click` https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/node.rb#L85 to do something similar to https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/actions.rb#L299

Thanks for your consideration, and thanks for maintaining Capybara!
