### ISSUE TITLE
Expose pending requests URI

### ISSUE THREAD

**Issue by juanca** [teamcapybara/capybara#2249]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: capybara-3.15.1
Driver Information (and browser if relevant): selenium-webdriver-3.142.4

## Expected Behavior

Raising an error on remaining pending requests should display more useful information -- like, the pending request URIs (at the very least). This would help developers understand the state of their tests. 

## Actual Behavior

My codebase is pretty convoluted but here is the gist of my issue. I run a test that makes an XHR into a controller-action -- keep in the mind that this particular XHR is not the testing subject. The controller-action attempts to contact an external URI but fails on a timeout because the external URI is fake. Capybara interprets the behavior as a failing assertion via pending requests because the fake URI timeout is longer than the Capybara pending requests time limit. 

Here is the output of the test:

```
Failures:

  1) I am a test
     Failure/Error: raise 'Requests did not finish in 60 seconds' if timer.expired?
     
     RuntimeError:
       Requests did not finish in 60 seconds
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara/server.rb:64:in `wait_for_pending_requests'
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara/session.rb:131:in `reset!'
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara.rb:315:in `block in reset_sessions!'
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara.rb:315:in `reverse_each'
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara.rb:315:in `reset_sessions!'
     # /Users/juanca/.rvm/gems/ruby-2.3.3@foo/gems/capybara-3.15.1/lib/capybara/rspec.rb:18:in `block (2 levels) in <main>'
```

I only found out which request was failing by logging the increment and decrement flows in the `Capybara::Server` class. I could perhaps look through my test logs but there are so many resources requested by my application that it seems like the wrong user interface for developers. 

## Steps to reproduce

I'm not sure what to do here. I'm hoping I explained the core of the problem. This might be better represented in another medium for feature requests but I am not sure where to go.
