### ISSUE TITLE
have_no_text and similar matchers raise ArgumentErrors with Ruby 3

### ISSUE THREAD

**Issue by dark-panda** [teamcapybara/capybara#2493]
The following raises an `ArgumentError` on Ruby 3.0.2:

```ruby
it 'raises an exception' do
  expect('<div></div>').to have_no_content
end
```

Output:

```
Failures:

  1) raises an exception
     Failure/Error: expect('<div></div>').to have_no_content

     ArgumentError:
       wrong number of arguments (given 0, expected 1+)
     # ./.bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/rspec/matchers.rb:130:in `have_text'
     # ./.bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/rspec/matchers.rb:166:in `block (2 levels) in <module:RSpecMatchers>'
     # ./spec/test.rb:26:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:138:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:137:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/3.0.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

This is because `#have_text's` prototype is `have_text(text_or_type, *args, **options)`, and in Ruby 2.7 `text_or_type` appears to be `{}` if you use `have_no_text`, while in Ruby 3.0 it raises an exception.

## Meta
Capybara Version:
3.35.3
