### ISSUE TITLE
The default `selenium_chrome_headless` causes error on CircleCI

### ISSUE THREAD

**Issue by okuramasafumi** [teamcapybara/capybara#2615]
## Reference

https://discuss.circleci.com/t/rspec-capybara-test-fails-with-unknown-error-devtoolsactiveport-file-doesnt-exist/42528/2

I encountered the exact problem described above, the fix mentioned there solved my problem.

## Meta
Capybara Version: 3.37.1

Driver Information (and browser if relevant): `:selenium_chrome_headless`

## Expected Behavior

The default `selenium_chrome_headless` driver works on CircleCI.

## Actual Behavior

It causes an error:

```
Selenium::WebDriver::Error::UnknownError:
            unknown error: Chrome failed to start: exited abnormally.
              (unknown error: DevToolsActivePort file doesn't exist)
              (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
          # #0 0x56330b52f463 <unknown>
          # #1 0x56330b2f38d8 <unknown>
          # #2 0x56330b31bb6a <unknown>
          # #3 0x56330b316c05 <unknown>
          # #4 0x56330b35a802 <unknown>
          # #5 0x56330b35a2af <unknown>
          # #6 0x56330b352443 <unknown>
          # #7 0x56330b3233c5 <unknown>
          # #8 0x56330b324531 <unknown>
          # #9 0x56330b581dce <unknown>
          # #10 0x56330b585192 <unknown>
          # #11 0x56330b56693e <unknown>
          # #12 0x56330b586103 <unknown>
          # #13 0x56330b559d85 <unknown>
          # #14 0x56330b5a70a8 <unknown>
          # #15 0x56330b5a7239 <unknown>
          # #16 0x56330b5c2492 <unknown>
          # #17 0x7fe3285a9609 start_thread
          # ./spec/system/user_spec.rb:37:in `block (3 levels) in <main>'
          # ./spec/rails_helper.rb:91:in `block (3 levels) in <top (required)>'
          # ./spec/rails_helper.rb:90:in `block (2 levels) in <top (required)>'
```

In the above backtrace, `visit users_path` causes the error.

## Steps to reproduce

Capybara related code:

```ruby
# rails_helper.rb
  driver = :selenium_chrome_headless
  Capybara.current_driver = driver

  config.before(:each, type: :system) do
    driven_by driver
  end
```

CircleCI config:

```yaml
orbs:
  browser-tools: circleci/browser-tools@1.4.0
  ruby: circleci/ruby@1.8.0

references:
  ruby_executor: &ruby_executor
    image: cimg/ruby:3.1-browsers

- steps:
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - ruby/rspec-test
```
